apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "terminal.labels" . | nindent 4 }}
  name: {{ include "terminal.fullname" . }}
type: Opaque
data:
  credentials: {{ .Values.credentials | b64enc | quote }}
