apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "terminal.labels" . | nindent 4 }}
  name: {{ include "terminal.fullname" . }}
spec:
  ports:
  - name: terminal
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    {{- include "terminal.selectorLabels" . | nindent 6 }}
