apiVersion: v1
kind: Service
metadata:
  name: charts
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app.kubernetes.io/name: okteto-charts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: charts
  labels:
    app.kubernetes.io/name: okteto-charts
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: okteto-charts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: okteto-charts
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"