# this will be replaced by Okteto during deployment
functionNamespace: $NAMESPACE
serviceType: ClusterIP

# okteto manages the RBAC 
rbac: false

# disabled by default to make development easier
basic_auth: false

gateway:
  resources:
    limits:
      memory: "120Mi"
      cpu: "50m"

faasnetes:
  resources:
    limits:
      memory: "120Mi"
      cpu: "50m"

queueWorker:
    limits:
      memory: "120Mi"
      cpu: "50m"

prometheus:
  resources:
    limits:
      memory: "512Mi"
      cpu: "100m"

alertmanager:
    limits:
      memory: "50Mi"
      cpu: "100m"

nats:
  resources:
    limits:
      memory: "120Mi"
    requests:
      memory: "120Mi"
      cpu: "100m"

ingress:
  enabled: true
  annotations:
     dev.okteto.com/generate-host: true

faasIdler:
  resources:
    limits:
      memory: "64Mi"
      cpu: "100m"

basicAuthPlugin:
  enabled: false
  resources:
    limits:
      memory: "50Mi"
      cpu: "20m"

