# this will be replaced by Okteto during deployment
functionNamespace: $NAMESPACE
serviceType: ClusterIP

# okteto manages the RBAC 
rbac: false

# disabled by default to make development easier
basic_auth: false

# generate the basic auth token automatically if enabled
generateBasicAuth: true

gateway:
  # set to false to disable scaling up from zero replicas https://docs.openfaas.com/architecture/autoscaling/
  scaleFromZero: true
  resources:
    limits:
      memory: "120Mi"
      cpu: "50m"

faasIdler:
  # Set to false to enable scaling down to zero replicas when function is idle
  dryRun: true
  resources:
    limits:
      memory: "64Mi"
      cpu: "100m"

ingress:
  enabled: true
  annotations:
     dev.okteto.com/generate-host: true

faasnetes:
  resources:
    limits:
      memory: "120Mi"
      cpu: "50m"

queueWorker:
    limits:
      memory: "120Mi"
      cpu: "50m"

prometheus:
  resources:
    limits:
      memory: "512Mi"
      cpu: "100m"

alertmanager:
    limits:
      memory: "50Mi"
      cpu: "100m"

nats:
  resources:
    limits:
      memory: "120Mi"
      cpu: "50m"

basicAuthPlugin:
  enabled: false
  resources:
    limits:
      memory: "50Mi"
      cpu: "20m"

