openfaas:
  basicAuthPassword: "Password123!"
  
  # set to true to generate a random password
  generateBasicAuth: false

  gateway:
    resources:
      limits:
        memory: "120Mi"
        cpu: "50m"

  faasIdler:
    # Set to true to disable scaling down to zero idle functions
    dryRun: false

    inactivityDuration: 15m
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"

  faasnetes:
    resources:
      limits:
        memory: "120Mi"
        cpu: "50m"

  nats:
    resources:
      limits:
        memory: "120Mi"
        cpu: "50m"

  basicAuthPlugin:
    resources:
      limits:
        memory: "50Mi"
        cpu: "20m"

  queueWorker:
    resources:
      limits:
        memory: "120Mi"
        cpu: "50m"

  # this will be replaced by Okteto during deployment
  functionNamespace: $NAMESPACE

