openfaas:
  basicAuthPassword: "Password123!"
  generateBasicAuth: true
  gateway:
    resources:
      limits:
        memory: "120Mi"
        cpu: "50m"

  faasIdler:
    # Set to true to disable scaling down to zero replicas when function is idle
    dryRun: false

    # If a function is inactive for 15 minutes, it may be scaled to zero
    inactivityDuration: 15m
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"

  faasnetes:
    resources:
      limits:
        memory: "120Mi"
        cpu: "50m"

  nats:
    resources:
      limits:
        memory: "120Mi"
        cpu: "50m"

  basicAuthPlugin:
    resources:
      limits:
        memory: "50Mi"
        cpu: "20m"

  queueWorker:
    resources:
      limits:
        memory: "120Mi"
        cpu: "50m"

  # this will be replaced by Okteto during deployment
  #functionNamespace: $NAMESPACE
  functionNamespace: 'faas-rberrelleza'
