{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  labels:
    {{- include "cloudide.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "cloudide.fullname" . }}
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Eclipse Theia"
  name: {{ include "cloudide.fullname" . }}
spec:
  rules:
    - host: okteto
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "cloudide.fullname" . }}
              servicePort: {{ .Values.service.port }}
