apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "tensorflow-notebook.fullname" . }}
  labels:
    app: {{ template "tensorflow-notebook.name" . }}
    chart: {{ template "tensorflow-notebook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /jupyter-notebook
            backend:
              serviceName: {{ include "tensorflow-notebook.fullname" . }}
              servicePort: 8888
          - path: /
            backend:
              serviceName: {{ include "tensorflow-notebook.fullname" . }}
              servicePort: 6006
