{{- if and .Values.jupyter.persistence.enabled (not .Values.jupyter.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "tensorflow-notebook.fullname" . }}
  labels:
    app: "{{ template "tensorflow-notebook.fullname" . }}"
    chart: "{{ template "tensorflow-notebook.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.jupyter.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.jupyter.persistence.size | quote }}
  {{ include "tensorflow-notebook.storageClass" . }}
{{- end }}
