apiVersion: v1
kind: Service
metadata:
  name: jupyter-{{ template "tensorflow-notebook.fullname" . }}
  labels:
    app: {{ template "tensorflow-notebook.name" . }}
    chart: {{ template "tensorflow-notebook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: jupyter
      protocol: TCP
      name: jupyter
  selector:
    app: {{ template "tensorflow-notebook.name" . }}
    release: {{ .Release.Name }}
