runtime: full

persistence:
  size: 1Gi

image:
  repository: theiaide/theia
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # If not set it will use the default
  name:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  
service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: "1"
    memory: 2Gi