apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "movies.fullname" . }}-job
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "movies.name" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}
          image: okteto/movies-api
          command:
            - yarn
            - load
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb
                  key: mongodb-password
            - name: MONGODB_USERNAME
              value: {{ .Values.mongodb.mongodbUsername }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.mongodbDatabase }}
            - name: MONGODB_HOST
              value: {{ .Release.Name }}-mongodb
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
