apiVersion: v2
name: wordpress
version: 7.3.9
appVersion: 5.2.3
description: Web publishing platform for building blogs and websites
icon: https://apps.okteto.com/wordpress/icon.png
keywords:
- wordpress
- cms
- blog
- http
- web
- application
- php
home: http://www.wordpress.com/
sources:
- https://github.com/bitnami/bitnami-docker-wordpress
maintainers:
- name: okteto
  email: hello@okteto.com
dependencies:
- name: mariadb
  version: 6.x.x
  repository: https://apps.okteto.com/
  condition: mariadb.enabled
  tags:
    - wordpress-database

