wordpressEmail: change-me@okteto.com
wordpressUsername: okteto
wordpressPassword: okteto
allowEmptyPassword: false

wordpressFirstName: FirstName
wordpressLastName: LastName
wordpressBlogName: User's Blog!

wordpressScheme: https

mariadb:
  db:
    name: okteto
    user: okteto

  rootUser:
    password: okteto

  master:
    persistence:
      size: 10Gi

persistence:
  size: 10Gi

resources:
  limits:
    memory: 2Gi
    cpu: 1

updateStrategy:
  type: Recreate

service:
  type: ClusterIP
  annotations:
    dev.okteto.com/auto-ingress: "true"
