services:
  vote:
    public: true
    image: okteto/vote:stacks
    replicas: 2
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi

  redis:
    image: redis
    ports:
      - 6379
    resources:
      cpu: 100m
      memory: 128Mi
      storage: 1Gi
    volumes:
      - /data
