{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inlets.serviceAccountName" . }}
  labels:
{{ include "inlets.labels" . | nindent 4 }}
{{- end -}}
