{{- range $name, $service := .Values.services }}
{{ if $service.volumes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ $name }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    stack.okteto.com/name: "{{ $.Release.Name }}"
    stack.okteto.com/service: "{{ $name }}"
    app.kubernetes.io/name: "{{ $name }}"
    app.kubernetes.io/component: "{{ $name }}"
    {{- range $key, $value := $service.labels }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  annotations:
    {{- range $key, $value := $service.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  serviceName: "{{ $name }}"
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      stack.okteto.com/name: "{{ $.Release.Name }}"
      stack.okteto.com/service: "{{ $name }}"
  template:
    metadata:
      labels:
        stack.okteto.com/name: "{{ $.Release.Name }}"
        stack.okteto.com/service: "{{ $name }}"
        {{- range $key, $value := $service.labels }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      annotations:
        {{- range $key, $value := $service.annotations }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
    spec:
      {{ if $service.stop_grace_period }}
      terminationGracePeriodSeconds: {{ $service.stop_grace_period }}
      {{ end }}
      initContainers:
        - name: "{{ $name }}-init"
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /data"]
          volumeMounts:
            - name: "pvc"
              mountPath: "/data"
      containers:
        - name: "{{ $name }}"
          image: "{{ $service.image }}"
          {{ if $service.command }}
          command:
          {{ if eq (typeOf $service.command) "string" }}
            - sh
            - -c
            - {{ $service.command }}
          {{ else }}
            {{- range $command := $service.command }}
            - {{ $command }}
            {{ end }}
          {{ end }}
          {{ end }}
          {{ if $service.args }}
          args:
            {{- range $arg := $service.args }}
            - {{ $arg }}
            {{ end }}
          {{ end }}
          {{ if $service.ports }}
          ports:
            {{- range $port := $service.ports }}
            - containerPort: {{ $port }}
            {{ end }}
          {{ end }}
          {{ if $service.environment }}
          env:
            {{- range $env := $service.environment }}
            - name: "{{ (splitn "=" 2 $env)._0 }}"
              value: "{{ (splitn "=" 2 $env)._1 }}"
            {{ end }}
          {{ end }}
          {{ if or $service.cap_add $service.cap_drop }}
          securityContext:
            capabilities:
              {{ if $service.cap_add }}
              add:
                {{- range $cap := $service.cap_add }}
                - {{ $cap }}
                {{ end }}
              {{ end }}
              {{ if $service.cap_drop }}
              drop:
                {{- range $cap := $service.cap_drop }}
                - {{ $cap }}
                {{ end }}
              {{ end }}
          {{ end }}
          {{ if and $service.healthchecks $service.ports }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ mustFirst $service.ports }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ mustFirst $service.ports }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          {{ end }}
          {{ if $service.resources }}
          resources:
            limits:
              {{ if $service.resources.cpu }}
              cpu: {{ $service.resources.cpu }}
              {{ end }}
              {{ if $service.resources.memory }}
              memory: {{ $service.resources.memory }}
              {{ end }}
          {{ end }}
          volumeMounts:
            {{- range $index, $volume := $service.volumes }}
            - name: "pvc"
              subPath: "data-{{ $index }}"
              mountPath: {{ $volume }}
            {{ end }}
  volumeClaimTemplates:
    {{- range $index, $volume := $service.volumes }}
    - metadata:
        name: "pvc"
        labels:
          stack.okteto.com/name: "{{ $.Release.Name }}"
          stack.okteto.com/service: "{{ $name }}"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{ if $service.resources }}
        {{ if $service.resources.storage }}
        {{ if $service.resources.storage.class }}
        storageClassName: {{ $service.resources.storage.class }}
        {{ end }}
        {{ end }}
        {{ end }}
        resources:
          requests:
            {{ if $service.resources }}
              {{ if $service.resources.storage }}
                {{ if $service.resources.storage.size }}
                storage: {{ $service.resources.storage.size }}
                {{ else }}
                storage: 1Gi
                {{ end }}
              {{ else }}
              storage: 1Gi
              {{ end }}
            {{ else }}
            storage: 1Gi
            {{ end }}
    {{ end }}
---
{{- end }}
{{- end }}
