apiVersion: v2
appVersion: "1.6.2"
description: Cloud-Native Chaos Engineering for Kubernetes Developers
name: litmus
version: 1.6.4
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - kubernetes
maintainers:
  - name: ksatchit
    email: karthik.s@mayadata.io
  - name: chandankumar4
    email: chandan.kumar@mayadata.io
icon: https://apps.okteto.com/litmus/icon.png
dependencies:
  - name: litmus
    version: "1.6.4"
    repository: "https://litmuschaos.github.io/litmus-helm"