{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  labels:
    {{- include "theia.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
    #nginx.ingress.kubernetes.io/auth-url: https://okteto.sf.okteto.net/auth/endpoint
    #nginx.ingress.kubernetes.io/auth-signin: "https://okteto.sf.okteto.net/#/login"
    #nginx.ingress.kubernetes.io/auth-snippet: |
    #  proxy_set_header x-okteto-namespace ramiro;
  name: {{ include "theia.fullname" . }}
spec:
  rules:
    - host: okteto
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "theia.fullname" . }}
              servicePort: {{ .Values.service.port }}
