{{- if .Values.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.token | b64enc | quote }}
{{- end -}}
