apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  serviceName: "{{ template "theia.fullname" . }}"
  replicas: 1
  selector:
    matchLabels:
      {{- include "theia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        dev.okteto.com/inject-token: "true"
      labels:
        {{- include "theia.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "theia.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "ssh-keygen"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: ramiro/ssh-keygen
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: data
            mountPath: /data
            subPath: ssh
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "theia.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: THEIA_PLUGINS
              value: /home/plugins
          ports:
            - name: http
              containerPort: {{.Values.service.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: data
            mountPath: /home/project
            subPath: data
          - name: data
            mountPath: /home/plugins
            subPath: plugins
          - name: data
            mountPath: /home/node/.ssh
            subPath: ssh
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ template "theia.name" . }}
          release: "{{ .Release.Name }}"
          heritage: "{{ .Release.Service }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
            requests:
              storage: {{ .Values.persistence.size | quote }}

