apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  serviceName: "{{ template "theia.fullname" . }}"
  replicas: 1
  selector:
    matchLabels:
      {{- include "theia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        dev.okteto.com/inject-token: "true"
      labels:
        {{- include "theia.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: cloudbin
          hostPath: 
            path: /var/okteto/cloudbin
            type: Directory
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "theia.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: ssh-key
          image: "{{ template "theia.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
          - sh 
          - -c
          - test -f /var/okteto/ssh/id_rsa && cat /var/okteto/ssh/id_rsa && exit 0; ssh-keygen -q -t rsa -N '' -f '/var/okteto/ssh/id_rsa' && cat /var/okteto/ssh/id_rsa.pub
          volumeMounts:
          - name: data
            mountPath: /var/okteto/ssh
            subPath: ssh
      {{- if .Values.repository }}
        - name: git-clone
          image: "{{ template "theia.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
          - sh 
          - -c
          - "test -d /home/project/.git && exit 0; git clone {{ .Values.repository }} /home/project"
          volumeMounts:
          - name: data
            mountPath: /home/project
            subPath: project
      {{- end }}  
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "theia.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
          - sh 
          - -c
          - (mkdir -p $HOME/.ssh && chmod 700 $HOME/.ssh && cp /var/okteto/ssh/* $HOME/.ssh/ && chmod 600 $HOME/.ssh/id_rsa*); PATH=$PATH:/var/okteto/bin node $HOME/src-gen/backend/main.js /home/project --hostname=0.0.0.0
          env:
            - name: THEIA_PLUGINS
              value: /home/plugins
          ports:
            - name: http
              containerPort: {{.Values.service.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: cloudbin
            mountPath: /var/okteto/bin
            readOnly: true
          - name: data
            mountPath: /var/okteto/ssh
            subPath: ssh
            readOnly: true
          - name: data
            mountPath: /home/project
            subPath: project
          - name: data
            mountPath: /home/plugins
            subPath: plugins
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ template "theia.name" . }}
          release: "{{ .Release.Name }}"
          heritage: "{{ .Release.Service }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
            requests:
              storage: {{ .Values.persistence.size | quote }}

