# Default values for movies.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: Always

ingress:
  annotations: {}

replicaCount: 1
resources: {}
