flux:
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  clusterRole:
    create: false
  registry:
    dockercfg:
      enabled: true
      secretName: "okteto-regcred"
      configFileName: /dockercfg/config.json
  extraContainers:
    - name: recv
      image: fluxcd/flux-recv:0.6.0
      args:
      - --config=/etc/fluxrecv/fluxrecv.yaml
      ports:
      - name: recv
        containerPort: 8080
        protocol: TCP
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
      volumeMounts:
      - name: fluxrecv-config
        mountPath: /etc/fluxrecv
  extraVolumes:
    - name: fluxrecv-config
      secret:
        secretName: flux-recv
        defaultMode: 0400
  memcached:
    maxMemory: 128

helm-operator:
  workers: 1
  createCRD: false
  helm:
    versions: "v3"
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  clusterRole:
    create: false
  git:
    ssh:
      secretName: "flux-git-deploy"
