minio:
  mode: standalone
  replicas: 1

  ingress:
    # we don't need to expose minio to the world
    enabled: false

  consoleIngress:
    # this exposes the UI
    enabled: true
    annotations:
      dev.okteto.com/generate-host: "true"

  tls:
    enabled: false

  metrics:
    serviceMonitor:
      enabled: false

  persistence:
    enabled: true
    size: 1Gi

  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 100

  service:
    type: ClusterIP

  serviceAccount:
    create: false
