minio:
  mode: standalone
  accessKey: ""
  secretKey: ""
  rootUser: ""
  rootPassword: ""
  replicas: 1

  buckets:
  - name: okteto
    policy: none
    purge: false

  ingress:
    enabled: true
    annotations:
      dev.okteto.com/generate-host: "true"

  tls:
    enabled: false

  metrics:
    serviceMonitor:
      enabled: false

  persistence:
    enabled: true
    size: 1Gi

  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 100

  service:
    type: ClusterIP

  serviceAccount:
    create: false
