minio:
  mode: standalone
  accessKey: ""
  secretKey: ""
  replicas: 1

  defaultBucket:
    enabled: false
    name: okteto
    policy: none
    purge: false

  ingress:
    enabled: true
    annotations:
      dev.okteto.com/generate-host: "true"

  tls:
    enabled: false

  metrics:
    serviceMonitor:
      enabled: false

  persistence:
    enabled: true
    existingClaim: ""
    size: 500Mb

  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 100

  service:
    type: ClusterIP

  serviceAccount:
    create: false
