apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flux.fullname" . }}-recv
  labels:
    app: "{{ template "flux.fullname" . }}"
    chart: "{{ template "flux.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  github.key: {{ required "A valid .Values.secret is required" .Values.secret | b64enc | quote }}
  fluxrecv.yaml: "Zmx1eFJlY3ZWZXJzaW9uOiAxCmVuZHBvaW50czoKLSBrZXlQYXRoOiBnaXRodWIua2V5CiAgc291cmNlOiBHaXRIdWIK"
