apiVersion: v1
kind: Service
metadata:
  name: {{ include "flux.fullname" . }}-recv
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: "{{ template "flux.fullname" . }}"
    chart: "{{ template "flux.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: recv
  selector:
    app: {{ template "flux.name" . }}
    release: {{ .Release.Name }}
