redis:
  auth:
    enabled: true
    password: ""

  architecture: standalone

  replica:
    replicaCount: 1

  master:
    persistence:
      size: 1Gi
    resources:
      limits:
        memory: 256Mi
        cpu: 500m
