
# available runtimes: go, python, dart, cpp, java, full
runtime: full

# run htpasswd to generate your value e.g `htpasswd -nb hello world`
htpasswd: "hello:$apr1$incJ7.H4$xCj1Iz2yCuo.cserwimyk0"

persistence:
  size: 1Gi

resources:
  limits:
    cpu: "1"
    memory: 2Gi